# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'WebServerIPhone' do
    pod 'CocoaAsyncSocket', '~> 7.5.0'
    pod 'CocoaHTTPServer', '~> 2.3'
    pod 'CocoaLumberjack', :git => 'https://github.com/EdgarHz/CocoaLumberjack.git', :branch => 'dev_printf'
end

